name: basic

on:
  workflow_dispatch:
    inputs:
      name: arg1
      type: string
      required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        id: echo
        run: echo ${{ inputs.name }}
