#!/usr/bin/env/gh shebang
name: basic

on:
  workflow_dispatch:
    inputs:
      positional_arg:
        decription: "TRequired first position argument"
        type: string
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        id: echo
        run: echo ${{ inputs.positional_arg }}
